spring:
  cloud:
    gateway:
      routes:
        - id: account-app
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**
          filters:
            - AuthenticationFilter

        - id: auth-app
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**





  application:
    name: BANK-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/